name: jin_ai_generator
description: "一个适合刚接触 AI 来做 Flutter 应用的库"
version: 1.0.2

homepage: https://github.com/jinguoliang/jin_ai_generator

repository: https://github.com/jinguoliang/jin_ai_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  http: ^1.5.0
  openai_dart: ^0.5.5

dev_dependencies:
  test: ^1.26.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec